version: "3"
services:
  miral-marketplace:
    build: ./marketplace
    container_name: miral-marketplace
    command: sh -c "nginx -g 'daemon off;'"
    ports:
      - 80:80

  miral-dashboard:
    build: ./dashboard
    container_name: miral-dashboard
    command: sh -c "nginx -g 'daemon off;'"
    ports: 
      - 81:81
