version: '3'
services:
  miral-server:
    build:
      context: .
    container_name: miral-server
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    restart: always
    ports:
      - 4000:4000
    links:
      - miral-database
  miral-database:
    container_name: miral-database
    image: mongo
    ports:
      - 27017:27017